apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdash
  labels:
    app: webdash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdash
  template:
    metadata:
      labels:
        app: webdash
    spec:
      containers:
      - name: webdash
        image: hakansson/webdash:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: IN_CLUSTER
          value: "inside"
        - name: CONN_PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webdash
  name: webdash
spec:
  ports:
  - port: 80
  selector:
    app: webdash
  type: ClusterIP
